### ISSUE TITLE
Tracking: Ready for outside collaboration through GitHub

### ISSUE THREAD

**Issue by NHDaly** [davidanthoff/fund.jl#9]
Duplicate of https://github.com/anthofflab/Mimi.jl/issues/150

**Comment by davidanthoff** [comment]
@NHDaly there will be a lot of activity on Mimi.jl going forward, we got a big grant from Sloan for that work. I'm not sure, but we might also have capacity to revisit this issue here. Probably best to sort this out over on the Mimi.jl issue in a few weeks.
